version: '3.8'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - leaky-bucket
    environment:
      - MONGO_INITDB_DATABASE=woovi-challenge
    restart: unless-stopped


  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: build
    env_file:
      - .env
    container_name: api
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    networks:
      - leaky-bucket
    command: bun --watch src/index.ts
    volumes:
      - ./src:/app/src

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - leaky-bucket
    command: redis-server --appendonly yes

networks:
  leaky-bucket:
    driver: bridge

volumes:
  mongodb_data: 
  redis_data: 